import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import dotenv from 'dotenv';
import nodemailer from 'nodemailer';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => console.error('MongoDB connection error:', err));

// Lead Schema
const leadSchema = new mongoose.Schema({
  type: { type: String, required: true },
  name: { type: String, required: true },
  email: { type: String },
  phone: { type: String, required: true },
  timestamp: { type: String, required: true },
  details: { type: String }
});

const Lead = mongoose.model('Lead', leadSchema);

// Configure Nodemailer transporter (Gmail SMTP)
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

// API Routes
app.post('/api/leads', async (req, res) => {
  try {
    const { type, name, email, phone, timestamp, details } = req.body;
    if (!type || !name || !phone) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Save to MongoDB
    const newLead = new Lead({ type, name, email, phone, timestamp, details });
    await newLead.save();

    // Option 1: Direct Gmail SMTP Notification
    if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
      try {
        const mailOptions = {
          from: process.env.EMAIL_USER,
          to: 'nealvacation0@gmail.com', // Always send to this mailbox
          subject: `New Lead [${type}] - ${name}`,
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #0F4C81; border-radius: 8px; padding: 20px;">
              <h2 style="color: #0F4C81; border-bottom: 2px solid #00B4D8; padding-bottom: 10px; margin-top: 0;">New Travel Inquiry Received</h2>
              <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; width: 120px; color: #5C6E84;">Inquiry Type:</td>
                  <td style="padding: 8px 0; font-weight: 600; color: #0A2342;">${type}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #5C6E84;">Name:</td>
                  <td style="padding: 8px 0; color: #0A2342;">${name}</td>
                </tr>
                ${email ? `
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #5C6E84;">Email:</td>
                  <td style="padding: 8px 0; color: #0A2342;"><a href="mailto:${email}" style="color: #00B4D8; text-decoration: none;">${email}</a></td>
                </tr>` : ''}
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #5C6E84;">Phone:</td>
                  <td style="padding: 8px 0; color: #0A2342;">${phone}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #5C6E84;">Details:</td>
                  <td style="padding: 8px 0; color: #0A2342; line-height: 1.4;">${details}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #5C6E84;">Submitted At:</td>
                  <td style="padding: 8px 0; color: #0A2342; font-size: 0.9em;">${timestamp}</td>
                </tr>
              </table>
              <div style="margin-top: 25px; font-size: 0.8rem; text-align: center; color: #94A6B8; border-top: 1px solid rgba(10,35,66,0.08); padding-top: 15px;">
                Generated by NealVacation Luxury Concierge System
              </div>
            </div>
          `
        };
        await transporter.sendMail(mailOptions);
        console.log(`Email successfully sent to nealvacation0@gmail.com for lead: ${name}`);
      } catch (mailError) {
        console.error('Nodemailer SMTP Error:', mailError);
      }
    } 
    // Option 2: Web3Forms API Notification (Zero-Activation Alternative)
    else if (process.env.WEB3FORMS_KEY) {
      try {
        const response = await fetch('https://api.web3forms.com/submit', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
          },
          body: JSON.stringify({
            access_key: process.env.WEB3FORMS_KEY,
            subject: `New Lead [${type}] - ${name}`,
            from_name: 'NealVacation Concierge',
            name: name,
            email: email || 'Not Provided',
            phone: phone,
            details: details,
            timestamp: timestamp
          })
        });
        const resData = await response.json();
        if (resData.success) {
          console.log(`Lead successfully forwarded via Web3Forms for: ${name}`);
        } else {
          console.error('Web3Forms API Error:', resData.message);
        }
      } catch (web3Error) {
        console.error('Web3Forms Request Error:', web3Error);
      }
    }
    else {
      console.log('Neither SMTP credentials nor WEB3FORMS_KEY are configured in .env. Lead saved to MongoDB but email notification skipped.');
    }

    res.status(201).json(newLead);
  } catch (error) {
    console.error('Error saving lead / sending email:', error);
    res.status(500).json({ error: 'Failed to save lead' });
  }
});

app.get('/api/leads', async (req, res) => {
  try {
    const leads = await Lead.find().sort({ _id: -1 }); // Get newest first
    res.status(200).json(leads);
  } catch (error) {
    console.error('Error fetching leads:', error);
    res.status(500).json({ error: 'Failed to fetch leads' });
  }
});

app.listen(PORT, () => {
  console.log(`Backend server running on port ${PORT}`);
});
